// src/alias_block_generator.rs — Generate PowerShell alias function code

use crate::alias_types::*;
use crate::usage;





const BANNER_LINE: &str = "################################################################################";





////////////////////////////////////////////////////////////////////////////////
//
//  generate
//
//  Given an AliasConfig, produce the complete alias block as a Vec of lines.
//  Includes opening/closing 80-char banner, version, DO NOT EDIT warning,
//  root function, and sub-alias functions with column alignment.
//
////////////////////////////////////////////////////////////////////////////////

pub fn generate (config: &AliasConfig) -> Vec<String> {
    let version = usage::VERSION_STRING;
    let mut lines = Vec::new();

    //
    // Header banner
    //

    lines.push (BANNER_LINE.to_string());
    lines.push ("#".to_string());
    lines.push (format! ("#  RCDir Aliases -- Generated by rcdir v{}", version));
    lines.push ("#".to_string());
    lines.push ("#  DO NOT EDIT: This block is managed by rcdir and will be replaced.".to_string());
    lines.push ("#  Run 'rcdir --set-aliases' to reconfigure, '--remove-aliases' to remove.".to_string());
    lines.push ("#".to_string());
    lines.push (BANNER_LINE.to_string());
    lines.push (String::new());

    //
    // Build function definitions: root + enabled sub-aliases.
    // Align names and bodies into columns.
    //

    let mut funcs: Vec<(String, String)> = Vec::new();

    // Root function
    funcs.push ((
        config.root_alias.clone(),
        format! ("{} @args", config.rcdir_invocation),
    ));

    // Sub-alias functions
    for alias in &config.sub_aliases {
        if alias.enabled {
            funcs.push ((
                alias.name.clone(),
                format! ("{} {} @args", config.root_alias, alias.flags),
            ));
        }
    }

    // Calculate column widths
    let max_name = funcs.iter().map (|(n, _)| n.len()).max().unwrap_or (0);
    let max_body = funcs.iter().map (|(_, b)| b.len()).max().unwrap_or (0);

    for (name, body) in &funcs {
        lines.push (format! (
            "function {:<width_name$} {{ {:<width_body$} }}",
            name,
            body,
            width_name = max_name,
            width_body = max_body,
        ));
    }

    //
    // Footer banner
    //

    lines.push (String::new());
    lines.push (BANNER_LINE.to_string());
    lines.push ("#  End RCDir Aliases".to_string());
    lines.push (BANNER_LINE.to_string());

    lines
}





#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn make_config (root: &str, invocation: &str, subs: &[(&str, &str, bool)]) -> AliasConfig {
        AliasConfig {
            root_alias:       root.to_string(),
            rcdir_invocation: invocation.to_string(),
            sub_aliases:      subs.iter().map (|(name, flags, enabled)| AliasDefinition {
                name:        name.to_string(),
                flags:       flags.to_string(),
                description: String::new(),
                enabled:     *enabled,
            }).collect(),
            target_scope:  ProfileScope::CurrentUserAllHosts,
            target_path:   PathBuf::new(),
            session_only:  false,
            what_if:       false,
        }
    }



    ////////////////////////////////////////////////////////////////////////////
    //
    //  generates_header_and_footer_markers
    //
    ////////////////////////////////////////////////////////////////////////////

    #[test]
    fn generates_header_and_footer_markers() {
        let config = make_config ("d", "rcdir", &[]);
        let lines = generate (&config);

        assert! (lines[0].starts_with ("####"));
        assert! (lines.iter().any (|l| l.contains ("#  RCDir Aliases -- Generated by rcdir v")));
        assert! (lines.iter().any (|l| l.contains ("#  End RCDir Aliases")));
    }



    ////////////////////////////////////////////////////////////////////////////
    //
    //  generates_root_function
    //
    ////////////////////////////////////////////////////////////////////////////

    #[test]
    fn generates_root_function() {
        let config = make_config ("d", "rcdir", &[]);
        let lines = generate (&config);

        assert! (lines.iter().any (|l| l.starts_with ("function d")));
        assert! (lines.iter().any (|l| l.contains ("rcdir @args")));
    }



    ////////////////////////////////////////////////////////////////////////////
    //
    //  generates_sub_aliases
    //
    ////////////////////////////////////////////////////////////////////////////

    #[test]
    fn generates_sub_aliases() {
        let config = make_config ("d", "rcdir", &[
            ("dt", "--tree", true),
            ("dd", "-a:d", true),
            ("ds", "-s", true),
            ("dsb", "-s -b", false),  // disabled
        ]);
        let lines = generate (&config);
        let text = lines.join ("\n");

        assert! (text.contains ("function dt"));
        assert! (text.contains ("function dd"));
        assert! (text.contains ("function ds"));
        assert! (!text.contains ("function dsb"));  // disabled
    }



    ////////////////////////////////////////////////////////////////////////////
    //
    //  full_path_invocation
    //
    ////////////////////////////////////////////////////////////////////////////

    #[test]
    fn full_path_invocation() {
        let config = make_config ("d", "& \"C:\\Program Files\\rcdir.exe\"", &[]);
        let lines = generate (&config);
        let text = lines.join ("\n");

        assert! (text.contains ("& \"C:\\Program Files\\rcdir.exe\" @args"));
    }



    ////////////////////////////////////////////////////////////////////////////
    //
    //  custom_root_alias
    //
    ////////////////////////////////////////////////////////////////////////////

    #[test]
    fn custom_root_alias() {
        let config = make_config ("tc", "rcdir", &[
            ("tct", "--tree", true),
            ("tcw", "-w", true),
        ]);
        let lines = generate (&config);
        let text = lines.join ("\n");

        assert! (text.contains ("function tc "));
        assert! (text.contains ("function tct"));
        assert! (text.contains ("tc --tree @args"));
    }
}
